### ISSUE TITLE
Por que QR-DA es un usuario y no una organizacion?

### ISSUE THREAD

**Issue by aasanchez** [qr-da/qr-da#10]
Solo pregunto :smile:

**Comment by zamuro** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

El día del evento creamos el usuario para crear los issues.

Tienes razón: Debería ser una organización.

Quienes tengan acceso al usuario, por favor creen la organización.

El 05/11/15 a las 18:24, Alexis Sánchez escribió:

> Solo pregunto :smile:
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/qr-da/qr-da/issues/10.

---

MSc. Ing. Manuel Lucena Pérez
Cisco Certified Network Professional®
3Com WAN-LAN Specialist®
GNU/Linux User #409072
Debian User #261
Venezolana de Tecnologías, S.A. - Chief Technical Officer
m: +58 412 5156029
skype: mlucenap
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJWPIpLAAoJELoVRjyX+zSbMpEH/i3IIZr0UongpMpDtHZVSU1P
dxYu1cx0ypR+lW+Pk2HbRrs8tcNO/awpYTcaAzx0lB8Y799NdQeo209P+USVaZ96
62fOyL/iF8hUG/QueOUev1kmZk6C5UrN/f7MQv/LsFs/9YcWAOnVM4n87bFJGxPO
07uXSeGf/qIRd3DoUVrkuDgvJQqfd2FyYg1201Fk8pX/VWHPvf89Fqfkdt7QkXeG
bo1DCHok++CBzTVDveVN5liT/UA/P0OgDPw0bcbWtOPOOlnamWEkwf4i+kwwn5dd
d3RmTbjGttYhy9SzE9gGmyNYAIpoPGkeoamLmisKDDF81LzQF0dugczECKuXX8o=
=atgD
-----END PGP SIGNATURE-----

**Comment by carloselhalabi** [comment]
Creo que @thephoenixbird tiene acceso al usuario.

**Comment by aasanchez** [comment]
No tiene que ser creado por el usuario QRDA, cualquiera puede hacerlo, de
preferencia los de la idea original de este proyecto, incluso eso sería lo
más conveniente

**Comment by ThePhoenixBird** [comment]
@zamuro nos haces los honores de crear la organización?

**Comment by zamuro** [comment]
Claro. Voy a eso.

2015-11-07 12:39 GMT-04:30 ThePhoenixBird notifications@github.com:

> @zamuro https://github.com/zamuro nos haces los honores de crear la
> organización?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/qr-da/qr-da/issues/10#issuecomment-154723944.

## 

MSc. Ing. Manuel Lucena Pérez
Cisco Certified Network Professional®
3Com WAN-LAN Specialist®
GNU/Linux User #409072
Debian User #261
Venezolana de Tecnologías, S.A. - Chief Technical Officer
m: +58 412 5156029
skype: mlucenap

**Comment by zamuro** [comment]
https://github.com/QRDA-VE

2015-11-09 7:14 GMT-04:30 Manuel Lucena mlucenap@venet.com.ve:

> Claro. Voy a eso.
> 
> 2015-11-07 12:39 GMT-04:30 ThePhoenixBird notifications@github.com:
> 
> > @zamuro https://github.com/zamuro nos haces los honores de crear la
> > organización?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/qr-da/qr-da/issues/10#issuecomment-154723944.
> 
> ## 
> 
> MSc. Ing. Manuel Lucena Pérez
> Cisco Certified Network Professional®
> 3Com WAN-LAN Specialist®
> GNU/Linux User #409072
> Debian User #261
> Venezolana de Tecnologías, S.A. - Chief Technical Officer
> m: +58 412 5156029
> skype: mlucenap

## 

MSc. Ing. Manuel Lucena Pérez
Cisco Certified Network Professional®
3Com WAN-LAN Specialist®
GNU/Linux User #409072
Debian User #261
Venezolana de Tecnologías, S.A. - Chief Technical Officer
m: +58 412 5156029
skype: mlucenap
