### ISSUE TITLE
Crear Website de qr-da github-page

### ISSUE THREAD

**Issue by aasanchez** [qr-da/qr-da#7]
Se sugiere crear el Website de QR-DA dentro de GitHub-Pages, esto para mantener todo el codigo dentro de la misma plataforma, facilitando asi el mantenimiento de este.

**Comment by ernestochapon** [comment]
Soy de la idea de que sea una landing page que de acceso hacia el resto de la red de trabajo de QR-DA (Wiki; Blog - si lo hubiera -; sistemas internos, etc.).

**Comment by aasanchez** [comment]
Exacto @3rn3st0 eso se puede hacer dentro de githubpages, podemos tener wiki, blog y demas cosas basicas, creo que en un comienzo del proyecto podremos sobrevivir con eso y luego que la necesidad nos lleve mas alla, la experiencia ha demostrado en las comunidades que queremos hacer las cosas en un comienzo con herramientas cada vez mas complejas y funcionales que se instalan y luego nadie las mantiene.... Asi que creo que seria bueno hacer las cosas de otra forma, algo basico para comenzar y luego si la cosa crece mucho y la necesidad nos lleva alla, hacer el esfuerzo buscar herramientas mas "complejas"

**Comment by lordvalor** [comment]
Inicialmente se estuvo pensando realizar con WP bajo el dominio qrda.com.ve. Seria bueno definir esto porque adicionalmente creo que se hara bajo org.ve, entonces la idea es definir acá si nos vamos por gh-pages para dar inicio al repo y crear la cara web de qrda.

**Comment by davidhdz** [comment]
Sigo siendo partícipe de la idea de una gh-page que apunte a qrda.com.ve (o qrda.org.ve)

**Comment by zamuro** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hola

¿Se pueden hacer ambas? un gh-page con info general y un subdominio
(tipo wiki.qrda.org.ve) apuntando a otro lado (ya en la empresa
tenemos los dominios parqueados y apuntando a nuestros servidores)

El 14/10/15 a las 07:58, David Hernández escribió:

> Sigo siendo participe de la idea de una gh-page que apunte a
> qrda.com.ve (o qrda.org.ve)
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/qr-da/qr-da/issues/7#issuecomment-148034011.

---

MSc. Ing. Manuel Lucena Pérez
Cisco Certified Network Professional®
3Com WAN-LAN Specialist®
GNU/Linux User #409072
Debian User #261
Venezolana de Tecnologías, S.A. - Chief Technical Officer
m: +58 412 5156029
skype: mlucenap
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJWHkvGAAoJELoVRjyX+zSb87wH/jzyKyiEnH3tP9WFVeSO/UkS
iuRrW6EH2GaXvlTr3osNRSh0sGgeLFdPrq5ujpmsXS90J0tbwNkdIsdtD0U1EZT7
opqWOHVv1jcN4sFria34xT16I+WJ/hQ+k/d4QLK4CzZDwIkI+/4ydaqR0LZvN4t2
wskz4o+yg6eYfwpFCuEQKU19YvfK6y1KEvpHy4FS0ln+et0Z0nA7FA6xpllgGQXy
P14XGVnIcZZV8PgYyW4wtB18OYMQz5bpMHLK6YCUThtEPuLBgtIRWhNL6DeAbaVw
TOIbdFJmrnfPXk6xEztzKrmWNcTX47xgWcp9tzxL9IHndytEGK8lYquRVWq/xdI=
=DTCF
-----END PGP SIGNATURE-----

**Comment by carloselhalabi** [comment]
Yo pienso que sería ideal lo que plantean @aasanchez, @3rn3st0 y @zamuro. GH-pages para el landing page con enlace a la wiki, o cualquier otro CMS (foros, etc.). :)

**Comment by lordvalor** [comment]
**Vamos a crear el repositorio entonces y empezamos a trabajar

**Comment by zamuro** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Ya el repo está creado (Es éste mesmo) ¿O prefieres uno nuevo para la
wiki?

El 16/10/15 a las 19:05, LordValor escribió:

> **Vamos a crear el repositorio entonces y empezamos a trabajar
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/qr-da/qr-da/issues/7#issuecomment-148865541.

---

MSc. Ing. Manuel Lucena Pérez
Cisco Certified Network Professional®
3Com WAN-LAN Specialist®
GNU/Linux User #409072
Debian User #261
Venezolana de Tecnologías, S.A. - Chief Technical Officer
m: +58 412 5156029
skype: mlucenap
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJWI4TnAAoJELoVRjyX+zSb+QoIAIaDd1AC+SowbE5H+hV5EHVg
f6fGTj7mhfh/9VffbnglazNe6dlyn/7A5Tgzl6cJpkLa5hJ2mAjMXFZCEijMz2CG
jD4TEnabBZ1PDfodgY3BzF7RdxSUL7HI72gbCogZtRANzH2Oc7vc4Ql04jRKt9UK
nvyvEqeryhDvYYUuo4ZOAy7c1+mlCNDuLodhPbzOd7MYvlRJgHuTps/OJe5AgkHa
f5Ano284trhVLtc2/8NiwZTAkIspwjGpQ5KzZVteKeEgdM/+D9XBySK9o9BNPZGE
DDAnTpEo7bSe9K45cOyzxQ6Bbz2GnudQK9/srYv7uiu0vwDFtcq1EJML56Rs34U=
=L1Zw
-----END PGP SIGNATURE-----

**Comment by carloselhalabi** [comment]
Éste fin de semana he dedicado un poco de tiempo a éste issue. Armé un esqueleto con Bootstrap para proponerlo y que vayamos trabajando sobre algo. Subiré el código al repo apenas estén de acuerdo todos.

Por cierto, el CSS es un asco; hay muchas cosas que se pueden agrupar aún (elementos, atributos). Sin embargo, monté un live preview y adjunté un screenshot por si no quieren abrir la web (que es adaptable):

![captura el 2015-10-18 a las 22 13 12](https://cloud.githubusercontent.com/assets/2533088/10568748/23bff480-75e6-11e5-9ff7-c5e142b1dafe.png)

El live preview: http://elhalabi.org/qrda

Saludos :)

**Comment by ernestochapon** [comment]
@carloselhalabi excelente. Pienso que, si no hay objeciones, subas el código de ese preview al repositorio aquí mismo en [QR-DA](https://github.com/qr-da/) y empecemos de una vez por todas a armar una estructura corporativa real. Por cierto, me parece que no nos deberíamos preocupar ahora mismo por el **CSS/HTML** eso podemos trabajarlo más adelante, cuando el contenido esté bien conformado.

**Comment by carloselhalabi** [comment]
# ping

**Comment by Richzendy** [comment]
@carloselhalabi sube el código! entre todos le vamos dando forma si hace falta!

**Comment by lordvalor** [comment]
Me parece Excelente. Upload el código y ahi ente todos, como dice @Richzendy  le vamos dando los ajustes.

**Comment by carloselhalabi** [comment]
Estoy en San Cristóbal y no traje mi laptop, apenas le ponga las manos encima subiré el código. Saludos.

**Comment by carloselhalabi** [comment]
El código está arriba, hice el pull request y el merge de un vez. 
Una de las ideas principales (que escuché en la reunión) era añadir un form para facilitar el contacto de las fundaciones con nosotros mismos, @Richzendy propuso:

http://blog.bismallion.com/sending-email-sendgrid-attachment-javascript/

Mañana prometo hacer algo con eso (ya he abierto una cuenta con mi nombre pero están verificando), hoy apenas he llegado de 12 horas de carretera y he trabajado todo el día. Si alguien quiere echarle un ojo antes, pues adelante :+1:

**Comment by aasanchez** [comment]
El administrador del perfil QR-DA que habilite la opcion de githubpage para que pueda cargar y verse ocmo qr-da,github.io mientras se le asigna un dominio

**Comment by Richzendy** [comment]
@zamuro ha creado la organización QR-DA, de forma tal que sea más fácil colaborar entre todos, he forkeado el proyecto de la web y lo he pasado para allá en https://github.com/QRDA-VE/Website  y he seteado github-pages para ese repositorio en http://qrda-ve.github.io/Website/  pueden conseguir ayuda de github pages acá:

https://help.github.com/categories/github-pages-basics/

Voy a proceder a cerrar este issue y de ahora en adelante seguimos el proyecto por allá, le voy a dar acceso de escritura a @carloselhalabi que es el papá del sitio web y siguen por allá los issues y la colaboración forkeando el proyecto y haciendo pull.

Si hay algo malo, por favor avisen,  la intención es ayudar y cualquier cambio realizado se puede reversar si hay algo indebido xD
